language: julia
julia:
  - release
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-biopython
  - wget hhttp://ftp.de.debian.org/debian/pool/main/m/mafft/mafft_7.205-1_i386.deb
  - sudo dpkg -i mafft_7.205-1_i386.deb
  
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("BiomolecularStructures"); Pkg.test("BiomolecularStructures"; coverage=true)'  
after_success:
  - julia -e 'cd(Pkg.dir("BiomolecularStructures")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'