site_name: BiomolecularStructures
site_author: Simon Malischewski Henning Schuhmann Philipp Gerling Simon Leßmann
repo_url: https://github.com/hng/BiomolecularStructures
theme: readthedocs
pages:
- ['index.md', 'Home']
- ['modules.md', 'Modules']
- ['kabsch.md', 'Kabsch Algorithm']
markdown_extensions: [mathjax]
docs_dir: 'docs'
